apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    app.kubernetes.io/name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.persistence.storageClass }}"
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  # Created only when user wants explicit PVC. The StatefulSet will also create volumeClaimTemplates by default.
